language: go
sudo: false

os:
  - linux
  - windows
  - osx
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
env:
  - GO111MODULE=on
install:
  #- go get -v golang.org/x/lint/golint
script:
  - go test
