language: go

os:
  - linux
#  - windows
  - osx
go:
  - 1.13.x
env:
  - GO111MODULE=on
install:
  - go get -v golang.org/x/lint/golint
script:
#  - golint -set_exit_status ./...
  - go test -race ./...
