language: go
dist: xenial

os:
  - linux
  - windows
  - osx
  
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x

env:
  - GO111MODULE=on

script:
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=freebsd go build
  - GOOS=windows go build
  - GOARCH=386 go build

  - go test -v
  - go test -race -v
