on: [push, pull_request]
name: Benchmark
jobs:
  Compare:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Fetch Repository
      uses: actions/checkout@v2
    - name: Run Benchmark
      run: go test -benchmem -run=^$ -bench . | tee output.txt
    - name: Get Previous Benchmark Results
      uses: actions/cache@v1
      with:
        path: ./.github/
        key: ${{ runner.os }}-benchmark
    - name: Save New Benchmark Results
      uses: rhysd/github-action-benchmark@v1
      with:
        tool: 'go'
        output-file-path: ./.github/output.txt
        external-data-json-path: ./.github/benchmark-data.json
        fail-on-alert: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-on-alert: true