on: [push, pull_request]
name: Security
jobs:
  Gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: -exclude=G103,G104,G601 ./...