on: [push, pull_request]
paths-ignore:
  - 'utils/bytebufferpool/**'
  - 'utils/colorable/**'
  - 'utils/encoding/**'
  - 'utils/fasttemplate/**'
  - 'utils/isatty/**'
  - 'utils/schema/**'
name: Security
jobs:
  Gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: ./...