on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
      	# go-version: [1.11.x, 1.12.x, 1.13.x, 1.14.x]
        go-version: [1.14.x]
        platform: [ubuntu-latest, windows-latest,  macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    #- name: Security
     # run: go get github.com/securego/gosec/cmd/gosec; `go env GOPATH`/bin/gosec ./...
    - name: Test
      run: go test -v
      # is the syntax correct below?
      # https://github.com/marketplace/actions/telegram-notify
    - name: Notify
      uses: appleboy/telegram-action@0.0.7
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          The ${{ github.event_name }} event triggered final step.
          echo This event is a pull request that had an assignee removed.